config/routes.rb
Lawfirm::Application.routes.draw do

  scope "(:locale)", locale: /ru|en/ do
    get 'about' => 'home#about', :as => 'about'
    get 'services' => 'home#services', :as => 'services'
    get 'contacts' => 'home#contacts', :as => 'contacts'
    match 'contact' => 'contact#new', :as => 'contact_new', :via => :get
    match 'contact' => 'contact#create', :as => 'contact_create', :via => :post
  end

  root :to => 'home#index'

  get '/:locale' => 'home#index'

end

app/models/message.rb
class Message < MailForm::Base
  attr_accessor :full_name, :email, :phone, :subject, :message

  validates :full_name, :email, :subject, :message, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  protected
  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
  end

  # ensure locale persists
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Message.new
    render partial: 'new'
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to('/'+locale.to_s, :notice => t(:message_delivered))
    else
      redirect_to('/'+locale.to_s, :alert => t(:message_error))
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
  end

  def services
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/_new.html.erb
<button type="button" class="form-close close"><%= I18n.t(:close) %></button>
<div class="form-wrapper">
<h2><%= t(:contact_us) %></h2>
<h5><%= t(:contact_us_text) %></h5>
<%= form_for @message, url: contact_create_path, name: 'contact-form', class: 'contact-form', method: 'post' do |form| %>
    <%= form.text_field :full_name, placeholder: I18n.t(:full_name) %>
    <%= form.text_field :email, placeholder: I18n.t(:email) %>
    <%= form.text_field :phone, placeholder: I18n.t(:phone) %>
    <%= form.text_field :subject, placeholder: I18n.t(:subject) %>
    <%= form.text_area :message, placeholder: I18n.t(:message_placeholder), :size => '20x5' %>
    <%= form.submit I18n.t(:submit), class: 'btn btn-info' %>
<% end %>
</div>

app/views/home/about.html.erb
<div id="about-page" class="pages">
  <div class="row">
    <div class="span4">
      <p class="lead"><%= t(:photo) %></p>
      <ul class="thumbnails" style="position: relative">
        <li class="photo">
          <%= image_tag('me.jpg', class: 'thumbnail', alt: '370x400') %>
        </li>
        <div class="about-sticker">
          <%= image_tag (locale == :en ? 'sticker2eng-small.png' : 'sticker2ru-small.png') %>
        </div>
      </ul>
    </div>
    <div class="span8">
      <p class="lead"><%= t(:about) %></p>
      <section>
        <div class="page-header name">
          <h2 class="name"><%= t(:longname) %><br>
            <small class="profession"><%= t(:profession) %></small>
          </h2>
        </div>
          <p><%= t(:about_text_html) %></p>
      </section>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('.about-sticker').draggable({
      handle: '.about-sticker-header',
      containment: "#about-page",
      scroll: false
  })
</script>

app/views/home/contacts.html.erb
<div id="contact-page" class="pages">
  <div class="row">
    <div class="span8">
      <p class="lead"><%= t(:roadmap)%></p>
      <div id="map-canvas" class="shadow-effect" style="height: 100%; width: 100%; margin-bottom: 20px">
        <img src="http://maps.googleapis.com/maps/api/staticmap?center=47.841218,35.1193228&zoom=16&size=640x480&scale=2&sensor=true&markers=color:blue%7Clabel:A%7C47.841218,35.1193228">
      </div>
    </div>
    <div class="span4">
      <p class="lead"><%= t(:address) %></p>
      <address>
        <%= t(:address_text_html) %>
        <abbr title="Phone">Tel:</abbr>&nbsp;061-707-97-79<br>
        <abbr title="Phone">Tel:</abbr>&nbsp;096 727-01-21<br>
        <abbr title="Phone">Tel:</abbr>&nbsp;050-202-16-18
      </address>
      <address>
        <strong><%= t(:myname) %></strong><br>
        <a href="mailto:a.v.barskaya@gmail.com">a.v.barskaya@gmail.com</a>
      </address>
      <p class="lead"><%= t(:open_hours) %></p>
      <address>
        <%= t(:open_hours_text_html) %>
      </address>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="home-page" class="pages">
    <div id="home-slide-wrapper" class="shadow-effect">
      <div id="home-slides" class="slide-1">
        <% i = 1; while i < 5 do %>
            <% slide_id = "slide-#{i.to_s}" %>
            <% slide_header = "slide_header_#{i.to_s}".to_sym %>
            <% slide_text = "slide_text_#{i.to_s}".to_sym %>
            <% slide_image = "slide_image_#{i.to_s}.jpg" %>
            <div id="<%= slide_id %>" class="row slides <%= 'active' if i==1 %>">
              <div class="span6">
                <div class="hero-unit">
                  <span class="slider-header"><%= t(slide_header).capitalize %></span>
                  <p class="slider-text"><%= t(slide_text).capitalize %></p>
                </div>
              </div>
              <div class="span6 slider-img-wrap">
                <%= image_tag(slide_image, :class => 'dropshadow slider-img') %>
              </div>
            </div>
        <% i+=1 %>
        <% end %>
      </div>
      <div class="row-fluid no-space slider-buttons">
        <div class="span3 active" value="slide-1"><h4><%= t(:together) %></h4></div>
        <div class="span3" value="slide-2"><h4><%= t(:connections) %></h4></div>
        <div class="span3" value="slide-3"><h4><%= t(:time) %></h4></div>
        <div class="span3" value="slide-4"><h4><%= t(:responsibility) %></h4></div>
      </div>
    </div>
    <div id="services" class="row-fluid no-space">
      <% i = 1; until i == 5 do %>
          <% services_header = 'services_header_'+i.to_s %>
          <% services_text = "services_text_#{i.to_s}_html" %>
          <div class="span3 service service<%= i.to_s %>">
            <a href="<%= services_path+"#service#{i.to_s}" %>">
              <h4 class="text-center"><%= t(services_header.to_sym).capitalize %></h4>
              <p>
                <% if locale == :en %>
                <%= truncate(t(services_text.to_sym), length: 250, separator: ' ') {raw(' &rarr;')} %>
                <% else %>
                <%= truncate(t(services_text.to_sym), length: 250, separator: ' ') {raw(' &rarr;')} %>
                <% end %>
              </p>
            </a>
          </div>
      <% i+=1  %>
      <% end  %>
    </div>
    <div id="reviews" class="row-fluid shadow-effect hidden-phone">
      <div class="row">
        <h2 class="text-center"><%= t(:reviews) %></h2>
      </div>
      <div class="reviews-wrapper">
        <% i = 1; while i < 5 do %>
        <% review_id = "review-#{i.to_s}" %>
        <% review_photo = "review_photo#{i.to_s}.jpg" %>
        <% review_name = "reviews_name_#{i.to_s}".to_sym %>
        <% review_title = "reviews_title_#{i.to_s}".to_sym %>
        <% review_text = "reviews_text_#{i.to_s}".to_sym %>
        <div id="<%= review_id %>" class="row review <%= 'active' if i==1 %>">
          <div class="review-wrapper">
            <div class="span2 review-photo">
              <%= image_tag(review_photo, :class => 'img-polaroid') %>
            </div>
            <h3><%= t(review_name) %></h3>
            <h4><%= t(review_title) %></h4>
            <br>
            <p class="lead">
              <em>
                <blockquote>"<%= t(review_text) %>"</blockquote>
              </em>
            </p>
          </div>
        </div>
        <% i += 1 %>
        <% end %>
      </div>
      <div class="row review-buttons">
        <div class="span4 offset4">
          <ul class="inline text-center">
            <li class="btn slide-circle active" value="review-1">1</li>
            <li class="btn slide-circle" value="review-2">2</li>
            <li class="btn slide-circle" value="review-3">3</li>
            <li class="btn slide-circle" value="review-4">4</li>
          </ul>
        </div>
      </div>
    </div>
</div>
<script type="text/javascript">
  $('a.brand').click(function(event){
      event.preventDefault();
  })
</script>

app/views/home/services.html.erb
<div id="services-page" class="pages">
  <div class="row">
    <div class="span12">
      <div class="service-banner text-right shadow-effect">
        <%= t(:services_banner_text_html) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span3">
      <p class="lead"><%= t(:services) %></p>
      <ul class="nav nav-pills nav-stacked" id="services-sidebar">
        <li><a href="#service1" data-toggle="tab"><%= t(:services_header_1).capitalize %></a></li>
        <li><a href="#service2" data-toggle="tab"><%= t(:services_header_2).capitalize %></a></li>
        <li><a href="#service3" data-toggle="tab"><%= t(:services_header_3).capitalize %></a></li>
        <li><a href="#service4" data-toggle="tab"><%= t(:services_header_4).capitalize %></a></li>
      </ul>
    </div>
    <div class="span9 tab-content">
      <p class="lead"><%= t(:description) %></p>
      <% i=1; while i < 5 do %>
      <% service_id = "service#{i.to_s}" %>
      <% service_text = "services_text_#{i.to_s}_html".to_sym %>
      <section class="tab-pane fade in" id="<%= service_id %>">
        <blockquote>
          <p>
            <small>
              <%= raw t(service_text) %>
            </small>
          </p>
        </blockquote>
      </section>
      <% i += 1 %>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        if(window.location.hash) {
            var url_hash_raw = window.location.hash;
            var url_hash = window.location.hash.slice(1);
            $('#services-sidebar li a').each(function(){
                if($(this).attr('href') == url_hash_raw){
                    $(this).parent('li').addClass('active');
                }
            })
            $('.tab-content section').each(function(){
                if($(this).attr('id') == url_hash){
                    $(this).addClass('active');
                }
            })
        } else {
            $('#services-sidebar').find('li:first').addClass('active');
            $('.tab-content').find('section:first').addClass('active');
        }
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : t(:myname) %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-42788033-1', 'abarskaya.com');
    ga('send', 'pageview');
  </script>
  <%= csrf_meta_tags %>
  <link rel="author" href="https://plus.google.com/109674655432573806233" />
  <link rel="author" href="https://twitter.com/go7hic" />
  <link rel="author" href="https://www.facebook.com/ronen.verdi" />
  <meta name="description" content="<%= t(:profession) %>">
  <meta name="author" content="Ronen Verdi">
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700|Roboto:400,300,500,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <%= yield(:head) %>
</head>
<body>
<div class="content container">
  <%= render partial: 'shared/header' %>
  <%= render partial: 'shared/flash_messages', flash: flash %>
  <%= yield %>
  <%= render partial: 'shared/footer' %>
  <div id="contact-form"></div>
</div>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer row-fluid container">
  <div class="span6">
    <%= link_to(t(:home), '/'+locale.to_s) %>
    /
    <%= link_to(t(:about), about_path) %>
    /
    <%= link_to(t(:services), services_path) %>
    /
    <%= link_to(t(:contacts), contacts_path) %>
  </div>
  <div class="span6">
    <p class="muted pull-right"><small><%= t(:copyright) %></small></p>
  </div>
  <div class="row-fluid">
    <div class="span12 text-center">
      <%= raw t(:dev_ref) + ' &rarr; ' %><a style="color: #08c" href="http://www.dedest.com">dedest.com</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to t(:profession)+' '+t(:myname), '/'+locale.to_s, class: 'brand hidden-phone' %>
      <%= link_to t(:myname), '/'+locale.to_s, class: 'brand visible-phone' %>
      <div class="nav-collapse">
        <%= menu_group do %>
            <%= menu_divider %>
            <%= menu_item t(:about), about_path %>
            <%= menu_divider %>
            <%= menu_item t(:services), services_path %>
            <%= menu_divider %>
            <%= menu_item t(:contacts), contacts_path %>
            <%= menu_divider %>
            <li class="dropdown visible-desktop">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag(:en == locale ? 'us-flag.png' : 'ru-flag.png') %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="nav-header"><%= t(:language) %></li>
                <li class="divider"></li>
                <%= menu_item 'English', '/en' %>
                <%= menu_item 'Русский', '/ru' %>
                <%#= menu_item 'English', locale: 'en' %>
                <%#= menu_item 'Русский', locale: 'ru' %>
              </ul>
            </li>
            <ul class="nav hidden-desktop">
                <li class="nav-header"><%= t(:language) %></li>
                <li class="divider"></li>
                <%= menu_item 'English', '/en' %>
                <%= menu_item 'Русский', '/ru' %>
            </ul>
            <%= menu_divider %>
        <% end %>
        <%= menu_group pull: 'right' do %>
            <li class="white contact-phone"><h4>096 727 01 21</h4></li>
            <%= menu_divider %>
            <li id="nav-message"><%= link_to image_tag('message.png', :id => 'nav-message-img') %></li>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation.old.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="navbar-inner">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to t(:myname), root_path, class: 'brand' %>
      <div class="nav-collapse">
        <ul class="nav" role="navigation">
          <li class="divider-vertical"></li>
          <li class="<%= 'active' if params[:action] == 'about' %>"><%= link_to(t(:about), about_path) %></li>
          <li class="divider-vertical"></li>
          <li class="<%= 'active' if params[:action] == 'services' %>"><%= link_to(t(:services), services_path) %></a></li>
          <li class="divider-vertical"></li>
          <li class="<%= 'active' if params[:action] == 'contacts' %>"><%= link_to(t(:contacts), contacts_path) %></li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" id="languages-label" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag(:en == locale ? 'us-flag.png' : 'ru-flag.png') %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="languages-label">
              <li class="<%= 'active' if params[:locale] == 'en' %>"><a tabindex="-1" href="<%= request.path %>?locale=en">English</a></li>
              <li class="<%= 'active' if params[:locale] == 'ru' %>"><a tabindex="-1" href="<%= request.path %>?locale=ru">Русский</a></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>
        </ul>
        <ul class="nav pull-right">
          <li class="white contact-phone"><h4>+ 38 (095) 6500869</h4></li>
          <li class="divider-vertical"></li>
          <li id="nav-message"><%= link_to image_tag('message.png', alt: 'message', id: 'nav-message-img') %></li>
        </ul>
      </div>
    </div>
  </nav>
  <%= nav_bar brand: t(:profession)+' '+t(:myname), brand_link: '/'+locale.to_s, responsive: true, inverse: true do %>
      <%= menu_group do %>
          <%= menu_divider %>
          <%= menu_item t(:about), about_path %>
          <%= menu_divider %>
          <%= menu_item t(:services), services_path %>
          <%= menu_divider %>
          <%= menu_item t(:contacts), contacts_path %>
          <%= menu_divider %>
          <%= drop_down image_tag(:en == locale ? 'us-flag.png' : 'ru-flag.png') do %>
              <%= menu_item "English", locale: 'en' %>
              <%= menu_item "Русский", locale: 'ru' %>
          <% end %>
          <%= menu_divider %>
      <% end %>
      <%= menu_group pull: 'right' do %>
          <li class="white contact-phone"><h4>096 727 01 21</h4></li>
          <%= menu_divider %>
          <li id="nav-message"><%= link_to image_tag('message.png', :id => 'nav-message-img') %></li>
      <% end %>
  <% end %>
</header>